Client.create(name: 'test', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence" , phone: "201-703-4560")
Client.create(name: 'test1', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")
Client.create(name: 'test2', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")
Client.create(name: 'test3', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")
Client.create(name: 'test4', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")
Client.create(name: 'test5', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")
Client.create(name: 'test6', street_address: '123 fake street', city: 'fake city', state: "fake state", zip: 99999, email:'fake@fake.com', refrence: "fake refrence", phone: "201-703-4560")



Job.create(client_id: 1, job_number: 1203, refrence: "Pete", schedule_date_month: 1, schedule_date_day: 1, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 2, job_number: 1204, refrence: "Pete", schedule_date_month: 1, schedule_date_day: 11, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1205, refrence: "Fred", schedule_date_month: 1, schedule_date_day: 13, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 4, job_number: 1206, refrence: "Fred", schedule_date_month: 1, schedule_date_day: 14, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 3, job_number: 1207, refrence: "Fred", schedule_date_month: 1, schedule_date_day: 15, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 5, job_number: 1208, refrence: "Fred", schedule_date_month: 1, schedule_date_day: 16, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1209, refrence: "Fred", schedule_date_month: 1, schedule_date_day: 1, schedule_date_year: 2019, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 4, job_number: 1213, refrence: "Pete", schedule_date_month: 1, schedule_date_day: 1, schedule_date_year: 2022, schedule_time: "15:30", time_arrived: "15:30", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1223, refrence: "Pete", schedule_date_month: 2, schedule_date_day: 1, schedule_date_year: 2016, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1233, refrence: "Pete", schedule_date_month: 11, schedule_date_day: 1, schedule_date_year: 2017, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1243, refrence: "Pete", schedule_date_month: 12, schedule_date_day: 1, schedule_date_year: 2018, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1253, refrence: "Linda", schedule_date_month: 5, schedule_date_day: 1, schedule_date_year: 2029, schedule_time: "15:30", time_arrived: "15:30", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1963, refrence: "Linda", schedule_date_month: 2, schedule_date_day: 1, schedule_date_year: 2018, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1273, refrence: "Linda", schedule_date_month: 5, schedule_date_day: 1, schedule_date_year: 2017, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1283, refrence: "Linda", schedule_date_month: 9, schedule_date_day: 1, schedule_date_year: 2018, schedule_time: "15:30", time_arrived: "15:30", time_completed: "17:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1593, refrence: "Linda", schedule_date_month: 10, schedule_date_day: 1, schedule_date_year: 2020, schedule_time: "15:30", time_arrived: "15:30", time_completed: nil, job_notes:"some note", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1243, refrence: "Linda", schedule_date_month: 3, schedule_date_day: 1, schedule_date_year: 2019, schedule_time: "15:35", time_arrived: "15:30", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 2222, refrence: "Pete", schedule_date_month: 3, schedule_date_day: 1, schedule_date_year: 1999, schedule_time: "15:35", time_arrived: "15:30", time_completed: nil, job_notes:"some note", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1333, refrence: "Pete", schedule_date_month: 3, schedule_date_day: 1, schedule_date_year: 2000, schedule_time: "15:35", time_arrived: "15:30", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 1443, refrence: "Pete", schedule_date_month: 3, schedule_date_day: 1, schedule_date_year: 2012, schedule_time: "15:35", time_arrived: "15:30", time_completed: nil, job_notes:"some note", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3211, refrence: "Pete", schedule_date_month: 7, schedule_date_day: 3, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: "12:45", job_notes:"some note", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3212, refrence: "Pete", schedule_date_month: 7, schedule_date_day: 27, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: "12:45", job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3213, refrence: "Linda", schedule_date_month: 7, schedule_date_day: 21, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3214, refrence: "Al", schedule_date_month: 6, schedule_date_day: 24, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: nil, job_notes:"some note", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3215, refrence: "Al", schedule_date_month: 5, schedule_date_day: 14, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: nil, job_notes:"none", description:"Job description onsite.")
Job.create(client_id: 1, job_number: 3216, refrence: "Al", schedule_date_month: 4, schedule_date_day: 10, schedule_date_year: 2018, schedule_time: "9:00", time_arrived: "9:15", time_completed: nil, job_notes:"none", description:"Job description onsite.")


Supplier.create(name: "fake supplier", address: "123 fake street, sometown. USA", refrence: "big al" )
Supplier.create(name: "fake supplier2", address: "123 fake street, sometown. USA", refrence: "big al" )
Supplier.create(name: "fake supplier3", address: "123 fake street, sometown. USA", refrence: "big al" )
Supplier.create(name: "fake supplier4", address: "123 fake street, sometown. USA", refrence: "big al" )
Supplier.create(name: "fake supplier5", address: "123 fake street, sometown. USA", refrence: "big al" )





MaterialPo.create(supplier_id: 1, job_id:1, description: "some material")
MaterialPo.create(supplier_id: 1, job_id:2, description: "some material")
MaterialPo.create(supplier_id: 1, job_id:1, description: "some material")
MaterialPo.create(supplier_id: 2, job_id:3, description: "some material")
MaterialPo.create(supplier_id: 4, job_id:4, description: "some material")
MaterialPo.create(supplier_id: 2, job_id:15, description: "some material a")
MaterialPo.create(supplier_id: 1, job_id:15, description: "some material b")
MaterialPo.create(supplier_id: 3, job_id:15, description: "some material c")
MaterialPo.create(supplier_id: 4, job_id:15, description: "some material")

User.create(username: "test1", email:"test1@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test2", email:"test2@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test3", email:"test3@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test4", email:"test4@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test5", email:"test56@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test6", email:"test6@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test7", email:"test7@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test8", email:"test56@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test9", email:"test6@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")
User.create(username: "test10", email:"test7@testing.com", phone: "864-703-4590", firstname: "test", lastname: "test", street_address: "123 fake street", city: "fake city usa", state: "ny", zip: 12321, password: "test")



Crew.create(user_id: 1, job_id: 1)
Crew.create(user_id: 1, job_id: 2)
Crew.create(user_id: 1, job_id: 3)
Crew.create(user_id: 2, job_id: 1)
Crew.create(user_id: 3, job_id: 1)
Crew.create(user_id: 2, job_id: 2)
Crew.create(user_id: 4, job_id: 3)
Crew.create(user_id: 5, job_id: 5)
Crew.create(user_id: 6, job_id: 2)
Crew.create(user_id: 1, job_id: 8)

Crew.create(user_id: 1, job_id: 9)
Crew.create(user_id: 1, job_id: 10)
Crew.create(user_id: 1, job_id: 11)
Crew.create(user_id: 1, job_id: 12)
Crew.create(user_id: 1, job_id: 13)
Crew.create(user_id: 1, job_id: 14)
Crew.create(user_id: 1, job_id: 15)
Crew.create(user_id: 1, job_id: 16)
Crew.create(user_id: 1, job_id: 17)
Crew.create(user_id: 1, job_id: 18)

Crew.create(user_id: 1, job_id: 20)
Crew.create(user_id: 1, job_id: 18)
Crew.create(user_id: 1, job_id: 19)
Crew.create(user_id: 2, job_id: 15)
Crew.create(user_id: 3, job_id: 15)
Crew.create(user_id: 4, job_id: 15)
Crew.create(user_id: 5, job_id: 15)
Crew.create(user_id: 6, job_id: 15)
Crew.create(user_id: 7, job_id: 15)
Crew.create(user_id: 1, job_id: 5)

Crew.create(user_id: 1, job_id: 21)
Crew.create(user_id: 2, job_id: 21)
Crew.create(user_id: 3, job_id: 21)
Crew.create(user_id: 4, job_id: 21)
Crew.create(user_id: 5, job_id: 21)
Crew.create(user_id: 6, job_id: 21)
Crew.create(user_id: 7, job_id: 21)
Crew.create(user_id: 8, job_id: 21)
Crew.create(user_id: 9, job_id: 21)
Crew.create(user_id: 10, job_id: 21)

Crew.create(user_id: 1, job_id: 22)
Crew.create(user_id: 1, job_id: 23)
Crew.create(user_id: 1, job_id: 24)
Crew.create(user_id: 1, job_id: 25)
Crew.create(user_id: 1, job_id: 26)
Crew.create(user_id: 2, job_id: 22)
Crew.create(user_id: 3, job_id: 24)
Crew.create(user_id: 4, job_id: 25)
Crew.create(user_id: 5, job_id: 26)
Crew.create(user_id: 6, job_id: 26)
